[build.environment]
  NODE_VERSION = "20"

[build]
  base = "website"
  publish = "dist"

[context.production]
  command = "VITE_HOSTNAME=$URL pnpm test"

[context.deploy-preview]
  command = "VITE_HOSTNAME=$DEPLOY_PRIME_URL pnpm test"

[[redirects]]
  from = "/index.md"
  to = "/locales/es_ES/index.md"
  status = 200
  force = true
  conditions = {Language = ["es_ES"]}